INSERT INTO roles (id, title)
values (1, 'STUDENT')
     , (2, 'USER')
     , (3, 'TEACHER')
     , (4, 'HEAD_TEACHER')
     , (5, 'DIRECTOR')
     , (6, 'EMPLOYEE')
     , (7, 'PARENT')
     , (8, 'ADMIN')
     , (9, 'SECRETARY')
     , (10, 'CLASS_TEACHER')